# Makefile - to compile samples

CC = gcc
CFLAGS = -Wall -std=c99 -g
ASFLAGS = -g

hello-puts: hello-puts.s
	
hello-printf: hello-printf.s

count-return: count-return.s

add-args: add-args.s

swap: swap.s

op-ex: op-ex.s

show-args: show-args.c

zips1: zips1.c

exercise-1: exercise-1.c

exercise-1-8: exercise-1-8.c

hello-c: hello-c.c

buftest: buftest.c

show-args: show-args.c

stringtest: stringtest.c

thread: thread.c

forktest: forktest.c

exploit: exploit.c

clean:
	-@rm *.o add-args count-return hello-printf hello-puts swap op-ex 2> /dev/null || true

