
CC = gcc
CFLAGS = -Wall -g

:.c
	$(CC) $(CFLAGS) -o $@ $?

zips1: zips1.c

exercise-1: exercise-1.c

exercise-1-8: exercise-1-8.c

hello: hello.c

buftest: buftest.c

show-args: show-args.c

stringtest: stringtest.c

thread: thread.c

forktest: forktest.c

exploit: exploit.c
